apiVersion: v2
appVersion: "0.3.5-hotfix"
description: A Helm chart for Kubernetes
name: ea-nws-website
type: application
version: 0.3.5-hotfix
dependencies:
  - alias: backend
    name: backend
    version: "0.3.5-hotfix"
    repository: file://charts/backend
  - alias: frontend
    name: frontend
    version: "0.3.5-hotfix"
    repository: file://charts/frontend