apiVersion: v2
appVersion: '0.4.7-patch3'
description: A Helm chart for Kubernetes
name: ea-nws-website
type: application
version: 0.4.7-patch3
dependencies:
  - alias: backend
    name: backend
    version: '0.4.7-patch3'
    repository: file://charts/backend
  - alias: frontend
    name: frontend
    version: '0.4.7-patch3'
    repository: file://charts/frontend
