apiVersion: v2
appVersion: '0.5.0'
description: A Helm chart for Kubernetes
name: ea-nws-website
type: application
version: 0.5.0
dependencies:
  - alias: backend
    name: backend
    version: '0.5.0'
    repository: file://charts/backend
  - alias: frontend
    name: frontend
    version: '0.5.0'
    repository: file://charts/frontend
