apiVersion: v2
appVersion: '0.4.4-patch'
description: A Helm chart for Kubernetes
name: ea-nws-website
type: application
version: 0.4.4-patch
dependencies:
  - alias: backend
    name: backend
    version: '0.4.4-patch'
    repository: file://charts/backend
  - alias: frontend
    name: frontend
    version: '0.4.4-patch'
    repository: file://charts/frontend
