apiVersion: v2
appVersion: '1.0.0'
description: A Helm chart for Kubernetes
name: ea-nws-website
type: application
version: 1.0.0
dependencies:
  - alias: backend
    name: backend
    version: '1.0.0'
    repository: file://charts/backend
  - alias: frontend
    name: frontend
    version: '1.0.0'
    repository: file://charts/frontend
