# Website in a single container
# To build container image run "BUILD_VERSION=1.0 docker compose build" or set BUILD_VERSION is .env
name: ea_nws_website
services:
  frontend:
    image: ea_nws_website_frontend:${BUILD_VERSION}
    build:
      context: ../
      dockerfile: docker/ea_nws_website/Dockerfile_frontend
      args:
        - NODE_ENV=${NODE_ENV}
        - REACT_APP_DOMAIN=${REACT_APP_DOMAIN}
    ports:
      - '3000:3000'
    networks:
      main:
        aliases:
          - frontend

  backend:
    image: ea_nws_website_backend:${BUILD_VERSION}
    build:
      context: ../
      dockerfile: docker/ea_nws_website/Dockerfile_backend
      args:
        - NODE_ENV=${NODE_ENV}
        - API_URL=${API_URL}
    ports:
      - '5000:5000'
    networks:
      main:
        aliases:
          - backend

  api:
    image: ea_nws_website_api:${BUILD_VERSION}
    build:
      context: ../
      dockerfile: docker/ea_nws_website/Dockerfile_api
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - '9000:9000'
    networks:
      main:
        aliases:
          - api

  nginx:
    image: ea_nws_website_nginx:${BUILD_VERSION}
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '7000:7000'
    networks:
      main:
        aliases:
          - nginx

networks:
  main:
