# Website in a single container
# To build container image run "BUILD_VERSION=1.0 docker compose build" or set BUILD_VERSION is .env
name: ea_nws_website
services:
  app:
    image: ea_nws_website:${BUILD_VERSION}
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - '9000:9000'
      - '5000:5000'
      - '3000:3000'
